// src/data/searchFilterOptions.js

export const makesByCategory = {
  car: [
    'All Makes',
    'Mercedes-Benz',
    'BMW',
    'Audi',
    'Rolls Royce',
    'Bentley',
    'Porsche',
    'Ferrari',
    'Lamborghini',
    'Volkswagen',
    'Toyota',
    'Honda',
    'Ford',
    'Chevrolet',
    'Nissan',
    'Hyundai',
    'Kia',
    'Mazda',
    'Subaru',
    'Lexus',
  ],
  motorcycle: [
    'All Makes',
    'Harley-Davidson',
    'Honda',
    'Yamaha',
    'Kawasaki',
    'Suzuki',
    'Ducati',
    'BMW',
    'Triumph',
    'Indian',
    'KTM',
    'Aprilia',
    'Moto Guzzi',
    'Royal Enfield',
    'MV Agusta',
  ],
  camper: [
    'All Makes',
    'Winnebago',
    'Airstream',
    'Forest River',
    'Thor Industries',
    'Fleetwood',
    'Newmar',
    'Tiffin',
    'Jayco',
    'Coachmen',
    'Keystone',
    'Dutchmen',
    'Grand Design',
    'Entegra',
  ],
  truck: [
    'All Makes',
    'Ford',
    'Chevrolet',
    'Ram',
    'GMC',
    'Toyota',
    'Nissan',
    'Dodge',
    'Mercedes-Benz',
    'Volvo',
    'Peterbilt',
    'Kenworth',
    'Freightliner',
    'Mack',
    'International',
  ],
  commercial: [
    'All Makes',
    'Mercedes-Benz',
    'Ford',
    'Volkswagen',
    'Fiat',
    'Peugeot',
    'Citroën',
    'Renault',
    'Iveco',
    'MAN',
    'Scania',
    'DAF',
    'Isuzu',
    'Mitsubishi',
  ],
};

export const modelsByMake = {
  'Mercedes-Benz': ['G-Class', 'S-Class', 'E-Class', 'C-Class', 'A-Class', 'GLE', 'GLC', 'AMG GT'],
  'BMW': ['3 Series', '5 Series', '7 Series', 'X5', 'X3', 'X7', 'M3', 'M5'],
  'Audi': ['A3', 'A4', 'A6', 'A8', 'Q5', 'Q7', 'Q8', 'e-tron'],
  'Rolls Royce': ['Cullinan', 'Ghost', 'Phantom', 'Wraith', 'Dawn'],
  'Bentley': ['Continental GT', 'Bentayga', 'Flying Spur', 'Mulsanne'],
  'Porsche': ['911', 'Cayenne', 'Panamera', 'Macan', 'Taycan'],
  'Ferrari': ['Roma', 'Portofino', '812', 'SF90', 'Purosangue'],
  'Lamborghini': ['Huracán', 'Urus', 'Revuelto'],
  'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'Polo', 'ID.4'],
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Land Cruiser', 'Yaris'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'Jazz'],
  'Ford': ['Focus', 'Fiesta', 'Mustang', 'F-150', 'Super Duty', 'Transit', 'Ranger', 'Explorer'],
  'Chevrolet': ['Camaro', 'Corvette', 'Tahoe', 'Silverado'],
  'Nissan': ['Qashqai', 'X-Trail', 'Leaf', 'GT-R', '370Z'],
  'Hyundai': ['i30', 'Tucson', 'Santa Fe', 'Kona', 'Ioniq'],
  'Kia': ['Sportage', 'Optima', 'Sorento', 'Stinger', 'EV6'],
  'Mazda': ['3', '6', 'CX-5', 'CX-30', 'MX-5'],
  'Subaru': ['Outback', 'Forester', 'Impreza', 'WRX'],
  'Lexus': ['IS', 'ES', 'RX', 'NX', 'LC'],
  'Harley-Davidson': ['Street Glide', 'Road Glide', 'Sportster', 'Fat Boy'],
  'Yamaha': ['MT-07', 'MT-09', 'R1', 'R6', 'NMAX'],
  'Kawasaki': ['Ninja', 'Z900', 'Versys', 'KLR650'],
  'Suzuki': ['GSX-R', 'V-Strom', 'Burgman', 'Hayabusa'],
  'Ducati': ['Panigale', 'Monster', 'Multistrada', 'Scrambler'],
  'Winnebago': ['Vista', 'Voyage', 'Adventurer', 'Revel'],
  'Airstream': ['Flying Cloud', 'International', 'Basecamp'],
  'Ram': ['1500', '2500', '3500', 'ProMaster'],
  'GMC': ['Sierra', 'Yukon', 'Acadia', 'Canyon'],
  'Dodge': ['Charger', 'Challenger', 'Durango', 'Ram'],
  'Volvo': ['XC90', 'XC60', 'S90', 'V90'],
  'Fiat': ['Ducato', 'Doblo', 'Scudo'],
  'Peugeot': ['Boxer', 'Partner', 'Expert'],
  'Renault': ['Master', 'Trafic', 'Kangoo'],
};

export const priceRanges = [
  'No limit',
  '€5,000',
  '€10,000',
  '€20,000',
  '€30,000',
  '€50,000',
  '€75,000',
  '€100,000',
  '€150,000',
  '€200,000',
  '€300,000',
  '€500,000',
];

export const registrationYears = [
  'Any year',
  '2024',
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  'Older',
];
