// src/data/autos.js
import image1 from '@/assets/images/Image1.jpeg';
import gWagon from '@/assets/images/G-wagon.jpeg';
import gwagon1 from '@/assets/images/Image3.jpeg';
import gwagon2 from '@/assets/images/Image6.jpeg';
import userLogo from '@/assets/images/png-clipart-user-profile-computer-icons-login-user-avatars-monochrome-black-thumbnail.png';

export const autos = [
  {
    id: "1",
    brand: "Rolls Royce",
    model: "Cullinan",
    version: "Black Badge",
    code: "RR-98432",
    price: 384900,
    year: 2021,
    engine: "6.75L V12 • 600 HP",
    transmission: "Automatic",
    drive: "AWD",
    mileage: 12000,
    location: "Düsseldorf, Germany",
    description: "British luxury icon. Hand-built perfection.",
    image: [image1],
    alt: "Rolls Royce Cullinan",
    vehicleType: "car",
    isHot: true,
    owners: 1,
    views: 2381,
    postedAt: "2025-01-05",
    isFinanced: false,
    sellerNote: "Машина полностью обслужена. Гаражное хранение.",
    seller: {
      id: "private_05",
      name: "Private Seller",
      type: "private",
      domain: "cars",
      hasPublicPage: false,
      memberSince: "2025-05-05",
      responseTime: "1 day",
      phone: "+49 123 456 7890",
    }
  },

  {
    id: "2",
    brand: "Bentley",
    model: "Continental GT",
    version: "W12 Speed",
    code: "BT-55720",
    price: 229000,
    year: 2020,
    engine: "6.0 W12 • 660 HP",
    transmission: "Automatic",
    drive: "AWD",
    mileage: 34000,
    location: "Berlin, Germany",
    description: "Handcrafted luxury grand tourer.",
    image: [image1],
    alt: "Bentley Continental GT",
    vehicleType: "car",
    isHot: false,
    owners: 1,
    views: 2381,
    postedAt: "2025-01-05",
    isFinanced: false,
    sellerNote: "Машина полностью обслужена. Гаражное хранение.",
    seller: {
      id: "private_03",
      name: "Private Seller",
      type: "private",
      domain: "cars",
      hasPublicPage: false,
      memberSince: "2025-02-05",
      responseTime: "1 day",
      phone: "+380 67 123 45 67",
    }
  },

  {
    id: "3",
    brand: "Mercedes-Benz",
    model: "G-Class",
    version: "G63 AMG",
    code: "MB-88301",
    price: 189900,
    year: 2019,
    engine: "4.0 V8 Biturbo • 585 HP",
    transmission: "Automatic",
    drive: "AWD",
    mileage: 45000,
    location: "Hamburg, Germany",
    description:
      "Luxury SUV with iconic design and top-tier performance.",
    image: [gWagon, gwagon1, gwagon2],
    alt: "Mercedes-Benz G-Class AMG",
    vehicleType: "car",
    isHot: true,
    owners: 1,
    views: 2381,
    postedAt: "2025-01-05",
    isFinanced: false,
    sellerNote: "Машина полностью обслужена. Гаражное хранение.",
    seller: {
      id: "dealer_01",
      name: "BMW Cars AutoSalon",
      logo: userLogo,
      type: "dealer",
      domain: "cars",
      hasPublicPage: true,
      rating: 4.8,
      votes: 312,
      memberSince: "2025-01-05",
      responseTime: "1 day",
      phone: "+49 123 456 7890",
    },
  },

  {
    id: "4",
    brand: "Bentley",
    model: "Continental GT",
    version: "V8 S",
    code: "BT-99214",
    price: 164900,
    year: 2018,
    engine: "4.0 V8 • 550 HP",
    transmission: "Automatic",
    drive: "AWD",
    mileage: 56000,
    location: "Munich, Germany",
    description: "Luxury performance coupe.",
    image: [image1],
    alt: "Bentley Continental GT",
    vehicleType: "car",
    isHot: false,
    owners: 1,
    views: 2381,
    postedAt: "2025-01-05",
    isFinanced: false,
    sellerNote: "Машина полностью обслужена. Гаражное хранение.",
    seller: {
      id: "dealer_02",
      name: "LuxuryCars AutoSalon",
      logo: userLogo,
      type: "dealer",
      domain: "cars",
      hasPublicPage: true,
      rating: 4.8,
      votes: 312,
      memberSince: "2025-01-05",
      responseTime: "1 day",
      phone: "+380 67 123 45 67",
    },
  }
];
